import Head from "next/head";
import Script from "next/script";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

import "@/styles/globals.css";

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <Script src="http://localhost:8097" />
        <title>Fernando Berrospi | Software Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <Script src="https://www.google.com/recaptcha/api.js" />
      </Head>
      <main>
        <Navbar />
        <Component {...pageProps} />
        <Footer />
      </main>
    </>
  );
}
